apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elasticsearch-snapshot
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: elasticsearch-snapshot
            image: gcr.io/host-project-shared-vpc/elasticsearch-snapshot:latest
            imagePullPolicy: Always
            env:
              - name: ELASTIC_HOST
                value: 10.156.0.96
              - name: REPO_NAME
                value: elasticsearch-catch-snapshot
          restartPolicy: Never
